[project]
name = "formula-ascent-api"
version = "1.0.0"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=25.1.0",
    "apscheduler>=3.11.2",
    "beautifulsoup4>=4.14.3",
    "fastapi[standard-no-fastapi-cloud-cli]>=0.136.1",
    "geopy>=2.4.1",
    "imbalanced-learn>=0.14.1",
    "joblib>=1.5.2",
    "lightgbm>=4.6.0",
    "lxml>=6.1.0",
    "markupsafe<3.0.4",
    "numpy>=2.4.4",
    "pandas>=3.0.3",
    "requests>=2.34.2",
    "scikit-learn<1.9.0",
    "timezonefinder>=8.2.4",
]

[project.optional-dependencies]
cpu = [
  "torch>=2.11.0"
]
cu128 = [
  "torch>=2.11.0"
]

[dependency-groups]
dev = [
    {include-group = "lint"},
    {include-group = "test"},
    "pre-commit>=4.6.0",
]
lint = [
    "ruff>=0.14.13"
]
test = [
    "pytest>=9.0.3",
    "pytest-asyncio>=1.3.0",
    "pytest-cov>=7.1.0",
    "pytest-xdist>=3.8.0",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "D100", "D101", "D102", "D103", "D104", "D107", "D401",
  "PLC0415",
  "PLR2004", "PLR0913", "PLR0915", "PLR0912",
  "S101",
  "ANN001", "ANN202", "ANN201",
  "TRY003", "TRY300",
  "SLF001",
  "ARG002",
  "E501",
  "RUF001",
  "FBT002", "FBT003",
  "EM102", "EM101",
  "BLE001",
  "DTZ001", "DTZ005", "DTZ007",
  "T201",
  "C901",
  "PLW0603",
  "D203", # causes incompatbility warning
  "D213", # causes incompatbility warning
  "COM812" # conflicts with formatter
]

[tool.setuptools]
packages = ["app"]

[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cu128" },
  ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu128", extra = "cu128" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
